### ISSUE TITLE
Fatal error: No accept header received on handshake response 

### ISSUE THREAD

**Issue by sebastianow** [chrome-php/wrench#11]
Hi,

im getting this error:

Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /usr/www/users/project1/vendor/chrome-php/wrench/src/Protocol/Protocol.php:469
Stack trace:
#0 /usr/www/users/project1/vendor/chrome-php/wrench/src/Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake('HTTP/1.1 403 Fo...', 'sAMPSpAnjWISD6x...')
#1 /usr/www/users/project1/vendor/chrome-php/chrome/src/Communication/Socket/Wrench.php(99): Wrench\Client->connect()
#2 /usr/www/users/project1/vendor/chrome-php/chrome/src/Communication/Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect()
#3 /usr/www/users/project1/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect()
#4 /usr/www/users/project1/vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium\Browser\BrowserProcess->start('chromium', Array)
#5 /usr/www/users/project1/acp/cmd-actions-1.php(59): HeadlessChromium\BrowserFactory->createBrowser(Array)
#6 {main}
  thrown in /usr/www/users/project1/vendor/chrome-php/wrench/src/Protocol/Protocol.php on line 469

Any ideas?

regards
Sebastian

**Comment by enricodias** [comment]
See https://github.com/chrome-php/chrome/issues/492

**Comment by GrahamCampbell** [comment]
This issue has been resolved in v1.8.1 of `chrome-php/chrome`.
