### ISSUE TITLE
Reason for requiring origin header?

### ISSUE THREAD

**Issue by NormySan** [chrome-php/wrench#15]
The wrench client requires an origin to be set and also includes in the comment that this is required in later versions of the WebSocket protocol? I've been trying to find information related to this but can't find anything related to this requirement.

The reason why I'm asking is because connecting to headless chrome instances does not work when the origin header is set because it will then attempt to validate the origin against allowed origins but when the origin header is removed everything works fine. So to get around this I had to use another WebSocker library that does not require an origin header to be set.

This is the error received from the headless chrome instance when an origin is set:

> Expected handshake response status code 101, but received 403. Rejected an incoming WebSocket connection from the http://127.0.0.1/ origin. Use the command line flag --remote-allow-origins=http://127.0.0.1/ to allow connections from this origin or --remote-allow-origins=* to allow all origins.

Thanks for creating a great library, it's awesome to not have to use a node instance running puppeteer anymore to be able to generate PDFs! 👍

**Comment by vrobert78** [comment]
I spent two days digging into this problem. I've just discovered your issue and agree it's a real problem!
I think I'll patch the code locally to interact with my headless chrome instance, but it would be nice to have a real solution.

Here's the line that causes the issue: https://github.com/chrome-php/wrench/blob/1.5/src/Protocol/Protocol.php#L348
